language: node_js

sudo: false

node_js:
- 8

env:
  global:
    - S3_BUCKET_PREFIX=hackingstudio-code4maus-projects
    - AWS_REGION=eu-central-1

cache: yarn

scripts:
  - yarn build

deploy:
  - provider: script
    skip_cleanup: true
    script: SLS_STAGE=staging yarn deploy
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: SLS_STAGE=prod yarn deploy
    on:
      branch: production
