theme: jekyll-theme-minimal

title: Programmieren mit der Maus - WDR
description: Spielerisches Erlernen von Programmierkonzepten
author: Hacking Studio
lang: de_DE
twitter:
  username: studiohacking
  card: summary_large_image
social:
  name: Hacking Studio
  links:
    - https://twitter.com/StudioHacking
    - https://github.com/wdr-data

logo: /images/logo.png
show_downloads: false
