service: hackingstudio-code4maus-app

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  role: 'arn:aws:iam::#{AWS::AccountId}:role/hackingstudio/code4maus/hackingstudio-code4maus-functions'
  stage: ${file(scripts/env.js):stage}

environment:
  S3_BUCKET_PROJECTS: ${self:custom.projectBucketName}

functions:
  prepareAssetUpload:
    handler: src/backend/prepareAssetUpload.handler
    events:
      - http:
          path: prepareAssetUpload
          method: POST

  saveProject:
    handler: src/backend/saveProject.handler
    events:
      - http:
          path: saveProject
          method: POST

resources:
  Resources:
    AppBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.appBucketName}
        WebsiteConfiguration:
          IndexDocument: index.html

    ProjectBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.projectBucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET]
              AllowedOrigins: ['*']
              Id: myCORSRuleId1
              MaxAge: '3600'
            - AllowedHeaders: [Content-Type]
              AllowedMethods: [PUT]
              AllowedOrigins: ['*']
              Id: myCORSRuleId2
              MaxAge: '1800'


plugins:
  - serverless-finch
  - serverless-pseudo-parameters
  - serverless-webpack

custom:
  appBucketName: hackingstudio-code4maus-app-${file(scripts/env.js):stage}
  projectBucketName: hackingstudio-code4maus-projects-${file(scripts/env.js):stage}
  client:
    bucketName: ${self:custom.appBucketName}
    distributionFolder: build
  webpack:
    webpackConfig: 'webpack.backend.js'
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk
